# -*- coding: utf-8 -*-
"""Encryption_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10T8lV55pf8-vovvpVxp56FTvUWKhXNzq
"""

import os
import time
import hashlib


def welcome_screen():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=" * 60)
    print(" ! Welcome to IS Project ! ".center(60))
    print("=" * 60)
    time.sleep(1)
    print("\nThis section demonstrates the ENCRYPTION + HASHING phase.")
    print("We will take your name, encrypt it, hash it, decrypt it, and verify it.")
    print("\nLet's begin! ")
    print("=" * 60)


def caesar_encrypt_letters(text, shift):
    encrypted_text = ""
    for char in text.upper():
        if 'A' <= char <= 'Z':
            # Shift within A-Z
            encrypted_char = chr((ord(char) - ord('A') + shift) % 26 + ord('A'))
            encrypted_text += encrypted_char
        # Skip non-letters or leave them out
    return encrypted_text


def caesar_decrypt_letters(cipher, shift):
    decrypted_text = ""
    for char in cipher.upper():
        if 'A' <= char <= 'Z':
            decrypted_char = chr((ord(char) - ord('A') - shift) % 26 + ord('A'))
            decrypted_text += decrypted_char
    return decrypted_text


def sha1_hash(text):
    text_bytes = text.encode('utf-8')
    return hashlib.sha1(text_bytes).hexdigest()


def main():
    welcome_screen()

    # ENCRYPTION PHASE
    plaintext = input("Enter the message to encrypt: ")
    while True:
        try:
            shift = int(input("Enter the encryption key: "))
            if 1 <= shift <= 25:
                break
            else:
                print("Shift must be between 1 and 25.")
        except ValueError:
            print("Please enter a valid integer.")

    cipher = caesar_encrypt_letters(plaintext, shift)

    # نطبّع النص (نخليه كله كابيتال) عشان الهاش قبل وبعد يكون لنفس الشكل
    normalized_plaintext = plaintext.upper()
    original_hash = sha1_hash(normalized_plaintext)

    print("\n==================== Encryption Output ====================")
    print(f"Plaintext: {plaintext}")
    print(f"Shift Key Used: {shift}")
    print(f"Cipher Text: {cipher}")
    print(f"SHA-1 Hash Value: {original_hash}")
    print("============================================================")

    # DECRYPTION PHASE
    cipher_input = input("\nEnter the cipher to decrypt: ")
    while True:
        try:
            decrypt_shift = int(input("Enter the decryption key: "))
            if 1 <= decrypt_shift <= 25:
                break
            else:
                print("Shift must be between 1 and 25.")
        except ValueError:
            print("Please enter a valid integer.")

    decrypted_message = caesar_decrypt_letters(cipher_input, decrypt_shift)

    print("\n==================== Decryption Output ====================")
    print(f"Decrypted message: {decrypted_message}")
    print("============================================================")

    # HASH VERIFICATION PHASE
    # نعيد حساب الهاش بعد فك التشفير (برضه نحوله لكابيتال عشان يطابق الأصلي)
    recomputed_hash = sha1_hash(decrypted_message.upper())
    integrity_ok = (original_hash == recomputed_hash)

    print("\n==================== Hash Verification ====================")
    print(f"Original Hash:   {original_hash}")
    print(f"Recomputed Hash: {recomputed_hash}")
    print(f"Integrity Verification: {'SUCCESS' if integrity_ok else 'FAILED'}")
    print("============================================================")


if __name__ == "__main__":
    main()